import { media } from './media/media.js';
import { loginEmailInput } from './components/loginEmailInput.js';
import { loginPasswordInput } from './components/loginPasswordInput.js';
import { loginSubmitButton } from './components/loginSubmitButton.js';
import { searchButton } from './components/searchButton.js';
import { clearSearchButton } from './components/clearSearchButton.js';
import { addUserButton } from './components/addUserButton.js';
import { loggedUserAvatar } from './components/loggedUserAvatar.js';
import { filters } from './components/filters.js';
import { editUserButton } from './components/editUserButton.js';
import { deleteUserButton } from './components/deleteUserButton.js';
import { backToSearchButton } from './components/backToSearchButton.js';
import { confirmDeleteUserButton } from './components/confirmDeleteUserButton.js';
import { cancelDeleteUserButton } from './components/cancelDeleteUserButton.js';
import { cancelEditorButton } from './components/cancelEditorButton.js';
import { saveButton } from './components/saveButton.js';
import { avatar } from './components/avatar.js';
import { editSettingsButton } from './components/editSettingsButton.js';
import { addDepartmentButton } from './components/addDepartmentButton.js';
import { addLocationButton } from './components/addLocationButton.js';
import { saveNewDepartmentButton } from './components/saveNewDepartmentButton.js';
import { saveNewLocationButton } from './components/saveNewLocationButton.js';
import { cancelNewDepartmentButton } from './components/cancelNewDepartmentButton.js';
import { cancelNewLocationButton } from './components/cancelNewLocationButton.js';
import { deleteDepartmentButton } from './components/deleteDepartmentButton.js';
import { deleteLocationButton } from './components/deleteLocationButton.js';
import { cancelDeleteDepartmentButton } from './components/cancelDeleteDepartmentButton.js';
import { cancelDeleteLocationButton } from './components/cancelDeleteLocationButton.js';
import { confirmDeleteDepartmentButton } from './components/confirmDeleteDepartmentButton.js';
import { confirmDeleteLocationButton } from './components/confirmDeleteLocationButton.js';
import { editDepartmentButton } from './components/editDepartmentButton.js';
import { editLocationButton } from './components/editLocationButton.js';
import { cancelUpdateDepartmentButton } from './components/cancelUpdateDepartmentButton.js';
import { cancelUpdateLocationButton } from './components/cancelUpdateLocationButton.js';
import { saveUpdateDepartmentButton } from './components/saveUpdateDepartmentButton.js';
import { saveUpdateLocationButton } from './components/saveUpdateLocationButton.js';

function addListeners() {
	media();
	loginEmailInput();
	loginPasswordInput();
	loginSubmitButton();
	searchButton();
	clearSearchButton();
	addUserButton();
	loggedUserAvatar();
	filters();
	editUserButton();
	backToSearchButton();
	deleteUserButton();
	confirmDeleteUserButton();
	cancelDeleteUserButton();
	cancelEditorButton();
	saveButton();
	avatar();
	editSettingsButton();
	addDepartmentButton();
	addLocationButton();
	saveNewDepartmentButton();
	saveNewLocationButton();
	cancelNewDepartmentButton();
	cancelNewLocationButton();
	deleteDepartmentButton();
	deleteLocationButton();
	cancelDeleteDepartmentButton();
	cancelDeleteLocationButton();
	confirmDeleteDepartmentButton();
	confirmDeleteLocationButton();
	editDepartmentButton();
	editLocationButton();
	cancelUpdateDepartmentButton();
	cancelUpdateLocationButton();
	saveUpdateDepartmentButton();
	saveUpdateLocationButton();

}

export { addListeners };